"""Add cpf column

Revision ID: 9277bb2509b3
Revises: 6c571282418a
Create Date: 2024-09-12 20:47:15.407134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9277bb2509b3'
down_revision: Union[str, None] = '6c571282418a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Adiciona a coluna cpf
        batch_op.add_column(sa.Column('cpf', sa.String(), nullable=True))

        # Cria a constraint de unicidade na coluna 'cpf'
        batch_op.create_unique_constraint('uq_users_cpf', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Remove a constraint de unicidade e a coluna 'cpf'
        batch_op.drop_constraint('uq_users_cpf', type_='unique')
        batch_op.drop_column('cpf')
    # ### end Alembic commands ###