apiVersion: v1
kind: ConfigMap
metadata:
  name: users-db-init
  namespace: user-auth
data:
  init-db.sh: |-
    #!/bin/bash
    set -e
    
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      SELECT 'CREATE DATABASE users_auth' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'users_auth');
    EOSQL