apiVersion: batch/v1
kind: Job
metadata:
  name: users-auth-migration
  namespace: users
spec:
  template:
    spec:
      containers:
      - name: migration
        image: kauan4453/users-microservice:latest

        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: users-auth-secret
              key: database-url
        command: ["alembic", "upgrade", "head"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      restartPolicy: OnFailure