apiVersion: batch/v1
kind: Job
metadata:
  name: users-auth-migration
  namespace: users
spec:
  template:
    spec:
      containers:
      - name: migration
        image: 131793876715.dkr.ecr.us-east-1.amazonaws.com/microservices/users:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: postgres-db
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: database-url
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        command: ["alembic", "upgrade", "head"]
      restartPolicy: OnFailure